apiVersion: v1
kind: Secret
metadata:
    name: registry-s3
    namespace: registry
type: Opaque
data:
    accesskey: ENC[AES256_GCM,data:73VjBwnRDeb6JeZgVVwZXAjyUB4CqvUpI4myyPwXxoVIkioL,iv:jz3mFhPjjRzgNZ/4Os5fwF2e+3SKjNujgxv63QZO0MI=,tag:q0TY45aRNnkbVgq8e3iL+Q==,type:str]
    secretkey: ENC[AES256_GCM,data:1eDhq5i3qCu6MqrmmQa0QPUESMw3f3NLtfX5fTkZUBhiwtO7wCzcrnhaRZbwXntbM8xBYxabuLJn05sARUxYV1LusSeBOulp7g10gPpjen9kov79NRezIQ==,iv:1ujIDqLMGKsQcRyn4ckutTJS7goTN+CCfYmunVvl03E=,tag:phjPMFIhgILiA8olz29/1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4d2p6QmxSQ2hHQmE1dmlL
            K3I2bTc5NzJRUFdNUFZUKzk2bUYwNi9jWHhVCnFldXZBajI4S2VZV1g2ektiWG5h
            VXZBTTViejVEWlRnaEU1a25qc1J5MmsKLS0tIHk3aEFac2NGRnF1czZKd1krZGZW
            cUN3UnZhV2pCcUNjd2xDbWgzMzBsakEKCNyOhNTRXwkIWk2vlEy2eduF9a5BfSA3
            G1ozwKVjpdyKasTaX+9Ll1AOJJyZQEproaFiP+LIhyPq9KK+uNn53g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:jEOuqdj++jeW/wnSDlxtsExFIUyIEGe784nCG7/1W3G00L2+UC8HYX9y5M4ep5YdLU3pIs8dL+mju2Hpp8jMRpdbzPE1R4l0r1NwaMV6f9mR+72S3aieC4EClWmvz3oIxth4LQKLRPYf7K1yw3NB+F5lWTlfCn7R/V3ChIKgCcE=,iv:ilk7JvWZb218En4IaRY1sdrnPLtFYmurJmhj1TR+eW8=,tag:y0Uf/vKm32Wi98neG9k9cw==,type:str]
    version: 3.13.3
