# The password for this namespace's cache (k8s/redis.yaml in the app repo). Prod and dev
# get different passwords, because they are different instances in different namespaces.
apiVersion: v1
kind: Secret
metadata:
    name: monke-app-redis
    namespace: yarn-monke-app-prod
stringData:
    password: ENC[AES256_GCM,data:Zgc2ukDML8uUU57zrMhCt3jOsCMi/7fQU77pDMoW2CI=,iv:3Ob4Xu9q+XP3EL1mxILl/NraTtCroWA9UP17+kA4/qA=,tag:WKMUwrYxkNJM6WXY4qmH6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUWxKWlpvSUI3aExrUklH
            aEFrdnIxNmVlclVRd2U2RmpFZzk4R0JiYVQwCis4My8yckdOclpuaVNmcjhCMHBO
            NDVpOUJxeXk3QzJCRW5qMGlLK1MvN28KLS0tIFFWSnJzSmJXYXlxdlFOWXFBNkky
            S1FqblFmT051cDVQTytPQThkWmVtdncKq07Sh6UUHfsc2ICqg8M0r9m+vZ+uc6YK
            KYnOZW+tnhr0ZlCjVYWPW8UCAja+YexEjilCkxZRyspcAqfayuPXSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T20:48:39Z"
    mac: ENC[AES256_GCM,data:S96mNMcQyAkNlDdN79x15TYOg/mETO9Bt7dMGpXD3hCXr+ME0W8bN/nvvjEF3pSYtVD+j+dOg0xgsZUK0m+8sm5VvvkbA36SubFHHaB8f8n81MhtibtUpznB0lUaTGrLmEpQNBeGOxAppIe+x70Qnlpvygba4aYIYcYywYbAtds=,iv:T5Wmyl8QZfcgiYjSlG3SdQMynCWa3lSCjdITcgA9cBg=,tag:mb5PCQnl6kKfYAdlUCggcg==,type:str]
    version: 3.13.3
