apiVersion: v1
kind: Secret
metadata:
    name: sops-test
    namespace: flux-system
stringData:
    canary: ENC[AES256_GCM,data:9cnNjdSSCfNnuMzAwOE+dsNWYRaX8f8RSgqCZZ+y2VNWFAyaFLCqeDkCPg==,iv:Op1q4/bBsDc2avLzd6FUaPI432MaNdq/yND+niN7jq8=,tag:NuBzkTKluu0rOTm5x9K2dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWTN4TmtQclNzazk1SGNP
            bXZ4Nmdsa0VxRWdRV1lHR1N3WnQydGErSlVFCmRFMEZKT1FwL3ZWMXdUQUw4d1FO
            RWFWOGhTV2xQWXlTNFVkZm1UOWZoRnMKLS0tIEk5Z0FpbEdmQS9LdlhOM09Tenpz
            RnNjblJTMmpxL2E3bll6ZFkvaXVsbGcKBLRf67OjzLTL7Fh9smDE17g4/p/7sZbO
            Nt00QJMjRRrN7/zo86Ypwek9rkVBqDZg/70Yxidxy2nWaNAfhJh35w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:33:15Z"
    mac: ENC[AES256_GCM,data:jmCjteR2Vl2gzvIbSosAlNEQTEx5lb3YSITPkb1utAiKCXMTzmgUkJwIQRImgaACNQhNwlA+t6oEp8yOFrk3DQ8NvlcvOGTEQVWvwoE50B2C1W2DkqIHv4z2MgB2XROkJfQAHUpPOGG5ok7CNaa2RfdY4sHtoutSTG8jgRzADog=,iv:zItDTARGJjAPNOhZUdAjjCUXo2xUxlSO8IIOQYSsl0A=,tag:Ult8oEKBSFvMCKeDBZG1bw==,type:str]
    version: 3.13.3
