apiVersion: v1
kind: Secret
metadata:
    name: cubesnail-pg
    namespace: cubesnail
type: Opaque
data:
    database: ENC[AES256_GCM,data:WYRZEqEIJ5j8HQIa,iv:Hz/4zdjDP8M2ZlXSgc/zqKmlcQJLe+Ch50hcv2ZiMro=,tag:ADnt/Tqx3KtyoOWDDtXOqw==,type:str]
    database_dev: ENC[AES256_GCM,data:/GvQvaO/Cmfc5nDgJpnN+bmkols=,iv:BPzX8IIws1PvPlC+GPNvkyJZsT1Z2MO9LHhc5PGQ15w=,tag:/dJ+e6uso9NEzIMkf58Whw==,type:str]
    host: ENC[AES256_GCM,data:kZHoIUc9v0j4Oc4YGjbmstSsQmbWuMbIgCEtWGMUmqg+GBCmAFT7aREj4g0=,iv:0kxBpTfLiYb2buycp3eO7nYIkmiw6GDlM9AlLtHcHeU=,tag:wv61/0g+S08y3GZP7XscVA==,type:str]
    password: ENC[AES256_GCM,data:T7aiCOaDcOA/A2Lj+lFq5FERExPmxOXkdctKoZMd4a0=,iv:Svucy8llQQbYIo2iisi0Vt/kb0h/yprwBBIv8AGLDRY=,tag:jug75670/Ui7TlJLIfcGFA==,type:str]
    port: ENC[AES256_GCM,data:m22pe2ubR1Q=,iv:jelAixe3vT0Xo+jUpChyVNddhrA6KLl1jI7R/s0c+wk=,tag:AnXiwI0iDoVSZwIMmRSXfQ==,type:str]
    uri: ENC[AES256_GCM,data:7tRZBxKfSpJJlQCcHmp+rcoo9YXMW/KSncCIVhObNrArNRlysIX8BBZtS9e62a4+ho0QJTKGpkzCcm0IX3Xo/Kc0zCkz1dMwdaII3G/WHJsdcYR9vKZpnBKKMM11L0UlaAIkFjQSRvZUsaB+DqtW/GGxmwJlMZjnHnhuSebgrVo=,iv:j8kXp+lMdbkPF2dqK2hFFrodTEABUzsawXRxcuOjtmE=,tag:wk20d/pxlH3rNFA608EyHw==,type:str]
    uri_dev: ENC[AES256_GCM,data:0M7eYqi31g+0yIayNB8ahQL8vXgZiWw4Hg4Kjh/1SUhXBjf6gBQWQd22Xii9FzWLCXnZVEe2kZV+ubX69qN/EcnMRUTnVvC0rKOygZ7qBw4jbzyPTko8dEF22iRDtb79A3XqALpuMjBa8eZxoBYYuRE7uQmFSK44kvVhXfFjt8lnAuPs,iv:KYwUsDVp+AwGxmHEdJbEVZRKO5OmXlakC8z2KZVG5/E=,tag:oYi4g1ndT1Kc2l5mvGeidw==,type:str]
    username: ENC[AES256_GCM,data:ybANeJuUrpGFSyLm,iv:xCAm25GYjDK/PXn+aGsU98k2CApv3ANO9xiSEMQGIKU=,tag:eFaAdnvmIRcy9UylgGOaVg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbjZNb2RyR1F2bWNhYkp4
            ZU9Ta09xV2s2ZFZRQ1lPVEd6ZmxSWHpWS1hZCngvVzczMUlXcm5RT0l1cktiREdH
            QkRIR3htYnFmcUp4SzRVKzRlOHlmTTQKLS0tIEx4cDg4cFBUNDhNYnVsam9pVTRo
            WVVBd0FiZHhGTHJPbG5TOFd6eXVpZlUKka40ZmUzj3KJTogpepn1xuHHbDP93C3E
            3AwHisSHztf7P5jkq1+ArH44GeDvKJ5gGB2cUj4jMYWFpwvIBjDyMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:0tMFt0x681IZcOccr/Vg7BJeo7Zby+7z4vdBH0vxGSQl+lDeKDuU2/nEJLTlc5qw25EgAvBgWwtPWDzZmyExfrFy29aQ6/mMGVOIbss9E6BACWrlSbRejNVssMKNXhfLqE2NDiejkcYn6H7C4muYAOLNmmdpYcsto9T3RlJtHHU=,iv:BFkgjzWd/f5VqqX5JM36GDZMyg4oX+Y7hNqWpFIVmvs=,tag:C0zajOErZkJzu34dAo5v0Q==,type:str]
    version: 3.13.3
