apiVersion: v1
kind: Secret
metadata:
    name: yarn-redis
    namespace: yarn
type: Opaque
data:
    host: ENC[AES256_GCM,data:A0Tfc9YUUig8Lx+p/xACgzMHOBnf5VnwJ3BJm+dSWJgO31IbTrcWoQ==,iv:ne/Pcjv8Zm0x5rr0LVxf/8DNs9MSwC4xiCoBd/KEcgo=,tag:urlpsukcaCOI9f4E8XHsvA==,type:str]
    password: ENC[AES256_GCM,data:F0/9SumepXe7CN8XpW3ViaLafHJ17A7NXxrUOZ+IemA=,iv:1UGJAHns0U1ipDbQMof4xztepZvEuKDVHWzT3EgOk3o=,tag:U8MP+JJvOMsY45c2bcJ87w==,type:str]
    port: ENC[AES256_GCM,data:pWu8q16xkJ4=,iv:OAZtOeWkPpLXWOYQYrPAbeeXT//zn9n4xOHr9a4aA9M=,tag:3CEOK3hndk3oKYnqBCdl0Q==,type:str]
    uri: ENC[AES256_GCM,data:cgOqHICrpwzQqAtIjZHSXngiC2T9AZ5C4OGMX99AJm9LHKI4+TIWsW31uOXuq4ciHMjIYczuxYiEcqq2Fbl9e2hccSwTcbRu3njGvcerelC+ygO76A+IpPSwiyw=,iv:Le25o0fwnnmdC5+OMCDPSi4Kq1WijxQ/HB0CP4cxVDg=,tag:eAFiZ9rznFRyyK4po9CsRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHa0g2YUdFZ0NWdzlYbzU0
            RUJ2YVA2bmtoNHhnUStNRCtnaFZHOWxVUFRJCkxnZWMvRFdnaEdxQU1FR2VVVlht
            N3Zia0JyZmQvSlJPUWZkREhrNVU1SWcKLS0tIGVDbnozb0V3LzNtc1c3RXo0dmdt
            elVQSWJZVFp3a0VsMndRVUxxZEhoMGMKYjtJUtHha1CGNfJcTM/f/b4Rxc5o33Sf
            dlnWc46GMkcuUaeajfE8KrqN+Yc9vRJhHq4FWjL5U7BesssvfQaFJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:tYWEWdgQY3JX8+82LFzR8GGp2pF+nlMrc4BR4cYJN0Cw7II+eQbxZl8uFxuPB27AN6tkK0iEiqj/95nqMkkURfjgoPbJw8SOpMVsEMgL2pV+M89Nl55SejGOJvUWm2UsCvFFBZ5UjhAeJm+oxsRbRaEY0ZVe7wU6kxi3EVXvnk0=,iv:6QGM72zYwbDCVuhDIzxTozHoxEJu2nlvXEKQOWoaOEQ=,tag:jvWHxf3ajcPACZoBSlX99g==,type:str]
    version: 3.13.3
