apiVersion: v1
kind: Secret
metadata:
    name: cubesnail-garage
    namespace: cubesnail
type: Opaque
data:
    access_key: ENC[AES256_GCM,data:E564NlVSlWabnpKSez2KW+jGBt7dqq3h1IIHBLMcP5gTtCEq,iv:zYODlI3GQM4H4YugunQOHpGX2FOA0oGYaIG7972yNzo=,tag:zBGcUkyi39v6ThSrcNN4gw==,type:str]
    bucket: ENC[AES256_GCM,data:XZQRZeSSuc2NasiZoyonHTy1kSQ=,iv:qUpbSVDfLtl9xLs5etg2R5wq5lEs2FSu/DtCe+yIW9U=,tag:DfEKg2ERDYNkPOTaTHABPg==,type:str]
    endpoint: ENC[AES256_GCM,data:zsOJ7ErYiacoCBiWpTcyDP/UDvS0bBkEXIVChQ//u8AkDedf5uSwfJCZHqhdB7vphzsiWOVKQXBi06/k88NN0hcMUWY=,iv:++1Vnzp/UmPvz9yUXPbT4Ocrtr5hsZ9fFC2ircSo0QQ=,tag:dsuzX7Xx98f+VnVSYGDJZg==,type:str]
    endpoint_external: ENC[AES256_GCM,data:eYiN/zdE32qlIAowq81dvV3tlktwCRl4fX8u9SMIjHELNHCL,iv:WcptqGyURlcb8y/jCT0B57gpe0V57iNoTB+1el710qc=,tag:QbAl5acBhqS4fF7mINIpqg==,type:str]
    secret_key: ENC[AES256_GCM,data:Alp5cPAxV68h3LisJ38gRuWNueVUDoO1onu6X/irCnGr8S0hLVdfa5D+SY0S99AIkO3TEbr9W92Bk/E7WEukXko1aZA5pKJYl+LXWtHl9en5TWmBdqrQHg==,iv:7ba6Md6IMFXS6uOSceq0zLYg1VmTlBaLsEuhh9SKXA4=,tag:PUhXT6kjRda4ZGDgYA52LQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQzNrS0EwMHVISFJCNHly
            Y05yQUplMk5vTENEYXlDVFpWZ3RVa1JJbUhZCkc5RXRxUE5SYmhIY3k1Y3RiWjhY
            VEh6ZG9Cc1JiMnJWTERBQWVVQzBOcEkKLS0tIEQ3dDRieE54MVNaWXpGUjFoRzZw
            c0tSLzZGcExtZGl1ZE9KOUtNYWZpR2cK3trNinuWG3tneuIzep8cHEXXnyPZTztR
            uNpOgrwe7FOILE2S4I+AXj1xuy1v6wDHE7GxvyNGEp1YuEU2rnkEng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:CnUhkEu7flVjanFZKBKYF++Fw7yPDdtmdHNWvQFfv/bqvZzOkhRRkUhEqK4upf57xrU2LnpYoaItzFTpN9KvGvCZcL76sk5f7YuQNe5FD8llLe3K7T3hiFfcXw08qmykU5NLNz13HqCmx5j+EEDyxOXzU8kpl7WUzBCbkaRz65Q=,iv:PggqTZrMiRnEO8Q7NtEIqzE/ElEPSwRXfZlvSPp6mB0=,tag:8PbGO8XX2cmm+JJALK/YuQ==,type:str]
    version: 3.13.3
