# The password for this namespace's cache (k8s/redis.yaml in the app repo). Prod and dev
# get different passwords, because they are different instances in different namespaces.
apiVersion: v1
kind: Secret
metadata:
    name: monke-app-redis
    namespace: yarn-monke-app-dev
stringData:
    password: ENC[AES256_GCM,data:kPdKYevJuiox3gHMP2ssqc48oi5nr3YPoKJholuK,iv:t7IbNzNgS/gO5VMhsQ7UMpSDzyYj8ZUiaZpjD6tq1hY=,tag:Hm6PcjFMeeksckn6XosrZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TGNZMk40RTAxK216eG1S
            dExQREsrbSthM3gzOUFVS09WbDJyWHpMd2tvCnBMUDlnVHo2TkE4UGQvS1JMK2Zo
            MUpOdWtaSkoyOU5NT0tKNkgzMmNGcm8KLS0tIE1qNUNLVW9XOGx1NlBnQnJ6YlRP
            UlluTk12UEFwQndNSWdwYXF3Y3FPQ2cK4kFd9vLWj1oFI9e+xKggsntdDRpwxg6O
            ub7Iei1VGJn0kGdqLi2WXJUnu771RY0Gp/cnvYa9wI65zZKNJr5Xig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T20:48:39Z"
    mac: ENC[AES256_GCM,data:eH/tnTZo5Z+mitTNEDvoFjpaIhJfeLHeJ9RRu2/u5hUHhsRN7pllerbPWChq0YE57I7mtbsQfxZ1c5WdYoS6f4umBwx8vRYEjffocHZD9HTy309vN79PzdjG6vC9PmW7OlkmjdKc9bHSq0SlfB97HDwoRGmGpRDOGtayXCDO0d0=,iv:2+19K+zWFUTH91qeeU7GK4yrsj7tFaWcjp5bSZw0uqo=,tag:0SYT/BBXlv3TTtoX9GrfqQ==,type:str]
    version: 3.13.3
