apiVersion: v1
kind: Secret
metadata:
    name: registry-creds
    namespace: cubesnail
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:G7YKqyqcWrRv+K1SbWT9prVaR44f8JXV30mkgUTCxa4NEPZniF7AS78UIkxZ18IJHOu6pBOI92ZavAEzJn1eXugWnnwbidJFOOB8/hXpgl0wDEaZECK9bIhHwhHALC/jHPUQcS625yVJxro96CQpUdyRwAzaeT+bRpDHjfgYc80OpZ9uUA1T5yYj6N2IWJMFUMjKhZEaUvZeZjmQZIgdmSLFHU4r33c/+KpfZJ1bbo4jmTGQHQ658ZK+CCcVZY2h,iv:jrPG0Io32MlsWIWqeCnWYlpJHxAU0V89dQIrwWfqSms=,tag:L3/IqoEnPFUWXajJSCAkeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbys0b2FDVVB0cXpVdHht
            aC90ZWhsV3lhelNKb2JGYnQ3SGRtYWwvSlJBClZERFZreUJwOWlRWEFsZWRYRElt
            ZDg1UG53UklYYkVmTDA3OTZHUFRPc1UKLS0tIEZZSDhTbURvSzd2MXg1ejhRcXRY
            NTlyZU1LL0FSZm5rWGJidk5aanA5OVkKzK3fk18XLCdbSK4pQmDS5NDDd5mtyiR1
            KRUPt/aPK81TzsbjDLx0xlLDUvzqSQGQw9JEmOxk2l8UrQGB3bIYoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:QzN9zlvQL2s3Q+zNXC54QaLt9m+WhByA6wjl8KSYoJy02KGVLz+2sA+Tk1yIV712wxSHdPh8o0a0y+C+UvhDpcwSGMDQsWr6xqHyOgZet1rqShMSHxqTA5CL59OAI/TOEwkwUsnavnyJSaoQAQ/RhVaSZ+kv1G1jcCycBUAKezs=,iv:cFCEi1voqvg/izx7yJgCOULBb9BN4YWNwf1mG8vG/rc=,tag:5PrhMGn1SPx3Oy9j5DOnwA==,type:str]
    version: 3.13.3
