apiVersion: v1
kind: Secret
metadata:
    name: cubesnail-redis
    namespace: cubesnail
type: Opaque
data:
    host: ENC[AES256_GCM,data:y0CpVaGe+1L0sGNHsvoSQPAP/l/5SEwKgknvE2BWB8m8wKMOkBJhlaqFToY=,iv:DzOIlrs5nzSv2AzJAhhhF1C4/S4gfrtvDjvDr7t7rTs=,tag:w7nwmJ0rYw+Q2Kf9nldVBw==,type:str]
    password: ENC[AES256_GCM,data:13ejh7BKPUUmTu/uG4ZIdRa9IFXfbHRKt6Bze4Het3w=,iv:tzV1gTJmSC23Iqzp8js4oUC/dK308H5yivKlznUhKDo=,tag:vE3+xBV6/ciwtcLfqMAmFg==,type:str]
    port: ENC[AES256_GCM,data:TtkxT6oRVoQ=,iv:OZlvJ2AqnOJG9yiFq41idvJd2em5lB4irkxOyrW+mRk=,tag:lQIFObs0lNPMKrSp0ANL7g==,type:str]
    uri: ENC[AES256_GCM,data:V1NgL849Txl3gC8FBgUvyOdrRc52JwlnLspbCTUdREhj0ZBFGO/FRAkaSBWie6JYHFzqQ8Y+76x2KlHS3ghd8rTj2z47Ebs6N6Z8Mcetupz4KuAk2bsaQFyur1adV59j/7UAIw==,iv:8ja6wgH8pCm/d08ANoVc6RCeLSbvxx58eDOqFElyeLI=,tag:FQVP5wahxi45BcytWUwM9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cjVkdzJ0TTBiYXZPeEVy
            U1FuVm9HRUJrSGQvUEZEc3JFcWhMUlJCUVFzCm9KNjUzOFVLMEswV2NPK1F1RXc0
            aHgzT1lRd3hqcXFMelRoNFZKRVFzSnMKLS0tIG5wajBMcTdCaXUva0hreW45eXk1
            cFR6N3BvUUh3aitJd2xGMm1oRWVoSEEKMBs2ixKXzcxo7DGsrYXecSgkR5xlmI4s
            S+9MT6Sqob0FdyY0m9EVjRcxXeMT5MknA1lyhgakHhcrn12vURRV0A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:iW+imcChv+jA8Gkw6tgnuakfSTY2CesyLUD1zMparmFvpwqob3o68v1r6CjCrptcV0Nvnx9WKqx9OpWXQrnW78cmGiMEASNRa7y4gOsJP+E+Jc3rHFF9j2WhSPlExyaABg0NydMLlE6OEy4eFsk+dxGvBVdY1OvDlAT3hhbjRMc=,iv:8Fah1GFdTJYeT6A3SusYt/KlJHGp9y+9i9AXv1R5DhQ=,tag:7BQVj3g+jfju8MScUGdBnA==,type:str]
    version: 3.13.3
