apiVersion: v1
kind: Secret
metadata:
    name: monke-ca-garage-key
    namespace: placeholder
type: Opaque
data:
    access_key: ENC[AES256_GCM,data:BNdDICjma+LNQX09xTmxDwhOTU0gfWp9GPjw1cBXXH3Y5+Ld,iv:d5Z2wvtuv1EDdyF6ea1dPGdigLHu49aT1Af1Yu70Jiw=,tag:syuOvObaWvhQEzlBCOEiJQ==,type:str]
    secret_key: ENC[AES256_GCM,data:QoQ1XP8aqDfMfe6Bqg9xUK8WbNMTGWf5WAcB3dXvBvSk+uWW0e/2I1FeDeG+3Xu5gkqF3lOvASd7U4pq38+40GhlIrijRfZvsSZp1wAIyWjMn0IiHZLYLA==,iv:xPLEkFSq7IRGfgstckbuOcQ/aMsoUXUPgHPR5NbL+o0=,tag:KN34Ri45RY3bpjFLaCN+sA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUU1LZ1BUTDl3WUt1Qm5l
            UVpaOTdFTGx0QUpXYXh3WDh2eEdLdHpFT3dBCkJxRU1lNGVXS0xmQ1F0NzRoZmk5
            Vm11YUpOYXRRWDZUc2RMV0twMmJ0TFkKLS0tIGRMc0xHOHFNRjA0bndETjZBUzZj
            bDhUNXpCcllxNWV5SEUrTFFtc0o2SzgKJOzCzdQowqedUJtHNeX9vYKAWax5H66t
            2VYLvqixOaCmviv5R3NmtJH5iLJaytbHo7gbvzZ7P9+/uHgnAs6wzg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:RB5d/jPor9x2WSMHDCbgAUl+s4nxYP55mUM6OcW0CIXCLiszXUdXjdMLu3uQVEKkWZQ4TnGnZoXYgTl5/s+W0hzOi5c+60o5AjEp27oijpSFk22BZcGed/9DmFliqvJv3640+AdVxxB/lAKGZM2Z/XtLEHt0+bwklkc72siOWgA=,iv:iA1n1YaIEyANaBa/y96+P+Sik0q5DDeXb716Xw/z1nI=,tag:TWZj6WZTaWQX0et8YNpPZA==,type:str]
    version: 3.13.3
