apiVersion: v1
kind: Secret
metadata:
    name: pg-app
    namespace: postgres
type: kubernetes.io/basic-auth
data:
    dbname: ENC[AES256_GCM,data:ZfHdMg==,iv:a6uPTo9SG2MogAJgORlohlc7hAOVLL6dLah0FPM0TzQ=,tag:ycGgXhm0HO7k8/9q8ojYkg==,type:str]
    fqdn-jdbc-uri: ENC[AES256_GCM,data:KtCndMeTb3n7HYQ7R2YoYicGQDVTMQw6rGdNLazyDpWKKeYbDsibTeNZjtVzOG0bspbhnofP7wJBK/hbLynsCgrgQsZWJRr2jawqqA2WyZn+ug8wS6RxzCPE65OH72SjDYkwIyOazme/mMqB9D0SEzN23VYMD2MdiMKlpClScbs2k5JnMCUDWMTjgfR41ZMYof9UwLLD1YcbmXzrmNJW0WaDutqk8Si1UDwisqjY61n04a50JmK2Sda6iS4XfqnA,iv:dZh4HDta+OsvDrOxaD6edG6RdzjZ6jMzAv7sbTfc7iI=,tag:pwLL+lU5MbjutuHvtQUW9w==,type:str]
    fqdn-uri: ENC[AES256_GCM,data:RdE1alctkD9xZXZ298eKnC/GFGruOQ4uivRbAwNaftha6sQ6JHxZ+VOWkctOTM7j0llsyBO4eD4SGBvduMpsTxJMZjAcwldiq9nXLvoCX2gTHiY3VWfqnFq9Z8Z6jlgj6PkJJzWEQgIERoKJInrvGwi+qYrVxpgV1jK16mBpCCCC2R1zUild7JeZRtBVqyv70Ou8oTIAsUbZZ1BEiK8FW/6jVjs=,iv:BC4Ttj44HNN9FafLbcpIyHsSIlTTbtdHoy3inmp3XcM=,tag:IdUbKJuqVV2G/NWY3TTvRw==,type:str]
    host: ENC[AES256_GCM,data:Nd59Zne5L4Q=,iv:FxNZ1c8u8N8P3PZzuNAn5sEty0B1rvIvdG4iWCljvcw=,tag:jdADw3+c+AgUlwLO0uQlww==,type:str]
    jdbc-uri: ENC[AES256_GCM,data:m07ZST8+fnV4G+c+kkC4FnGD9ZzQH/5cksoDRXHKBc+rAW7XTxMkmNnUaZ1o5eqI2txYMGcl4yNBNBQNyYv8zBhiWrxWzCoP92UABf53OXyWoyNoypk37vL1fs7V13kTxbcv5+RbUA/1d+9p0zt6PotU0Qmdd+YfZzi32diV2qcLb2Fhg4s+e+ZYjffe1UK5VGqbFgm95d3RQNwO+wTWmpgqd6Ot14UA,iv:0SzmdM5W45cFRX7AfwMKSJKNmA8lFcqzUgv+QhvV3II=,tag:ezhOVSPC6axMsoS14q2WAg==,type:str]
    password: ENC[AES256_GCM,data:UIv1infH3peHmQ58OZS7tNnlCjqRrsJX9wH5bWVTrVPPpltakvFdVIDrJ1e9RsO9nex1k9FfMIt8S2XNXBRYOUH4Cic4wPDRaV8pXgVWC9Ye/ygBXUxUFw==,iv:02Z4/1wgCzM5GAl20xx5tUiB5JkmipCxxtesUQCzmuY=,tag:LC6SJ3zM2mutldO/SzLbXQ==,type:str]
    pgpass: ENC[AES256_GCM,data:AaFEENA+AqEZOLPrA8BsdSMakdx96sbZyDwXmoFqyCWmGd6CF1asCNSy6eH3W3nZXIaKVilbg6lR6kQHw27tyXftJqZ8Zwyhtm4KQNoPaJuj1CDA581vSl7E7in/N78UAWQ7463mver2rN75kaN0zw==,iv:+VxTx/hYUB36oFnu3Yk+cUG3HfBRDDbBd+vvGegzoh8=,tag:Ay2vJpcfw7uUTU0tdCly8g==,type:str]
    port: ENC[AES256_GCM,data:wE/kmwfvfag=,iv:bsrWVoNo6IRv5l6KM+GxV3T4K9BtQ/6vgyg2CbXxtgc=,tag:FMMLz2AtWtDlDm1EnwnaGA==,type:str]
    uri: ENC[AES256_GCM,data:gprhX44MFZHiv6dBLLynrHa5OVChv+BBUQQACgJptasCpHiAKUtuZA/iw7CveFDavqZX9G6R/wJQLtN8bFvh7yAn3k44Je5eK9g+LqtS0cKg1hihUDpmP+7/RDhJIqcRHpu+QPE/JRNrNhIyXRJ12jl119AzvbEa9quNr04m2sfkD06NbrUmkjWEgq4=,iv:JBgFL072jx6+pZwiRwPUuHMe4qscNUMEnM1nHcDvn/M=,tag:QnL+g3uRJ7PTNHAcsv4skQ==,type:str]
    user: ENC[AES256_GCM,data:kmutOg==,iv:wj0JXn1M6lQ1KjY+Bcgpu35I/uRVrBhIFaudu8aniSc=,tag:d2b04xIhhh7tRkK4qXMgqA==,type:str]
    username: ENC[AES256_GCM,data:ZjEJrA==,iv:7Kk3TZ7cEXIxb70L74Oyu/3DaXcQgYG+VWJO4qYdq2o=,tag:2swOne3eDrDxNUpgqhAR/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT0laK1d4alB6TGNDYitD
            Ym91S253NWluZkNxTEZWQkFzTlRvVVlLa1hjCjJDOWVqdE9kV1hxdk42QzdpN2po
            Ny9kd1kza1VTL2FwVXcxRVpaamFMa0UKLS0tIFQvZWN6eU5qNStNcC9QQURYNncz
            dmNhS3VJeSttS3FobWNZNllCeFI3UnMKMVpBbL84KkNC3E7yd9fBTDgUDgllFhvS
            JnHrG0Qfy7PFAtfx9PETgVx6DUoJY/JJWOiEu5plEmdCQlb/qiXq9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:ILO+TQyyJL/FPQX5BSh91/GFDk/EC+POfdKEHZA0dKXTW5LWZDE1cPIkaeJ17YZPFM+afB6DYaH5xlJjJLXoZ4nhybdcL0IgMxrBpfGmkE00B7QQ83XX2CxTPXwcauBtvgCdrRf5XqDdwhb1VUTw3HfM+200Qw//0p+0rJSKFbg=,iv:5CCtMiShGLX/BwsV9mjCBcLoXi+fgs3tHlQk0WnNftc=,tag:1HZYmQetYSXbnURfPAjoBg==,type:str]
    version: 3.13.3
