apiVersion: v1
kind: Secret
metadata:
    name: registry-auth
    namespace: registry
type: Opaque
data:
    htpasswd: ENC[AES256_GCM,data:rY/exy57JfwQ7v2MBI+5MFAU5vvchUJl2UPi3hT0wYBt4KntC6I0LBPkksrsG1bsnCbGAsUUZFbaINxSXqhtFv+Row8Wjw0o2WwjmwEayY2YqNO35bXa/B+rPCTa8iaTwvMLnfjEFICcASSsWotMzJ/knEraf9FcZGGA2a/lHls7jeOfohjtbh4T/eMNEm1Z75/yV6c8MimFY3uX++CcjfHtMRzA+wwZdw4em9K835AOngtP4HO8zx4G/zmi9lL0jyUtXAdMqRi0kB5IEWt4JjQuHCq0syNTJdP2G1AsROmPEqMzHGJ78GDnS9i4JzCKWNXiMGmPm4AJZ7x+Tg1Pvozd8i7tzBhonl8HZJOL5VA=,iv:uEaHlwuIU0xnh5qtH/XrZk0nuVwqfJ9v0xM8yh0a/bw=,tag:6mDudAV5fDBBu7iDqjSDCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS1U5bW9zOWNuNDVKcGkv
            SnBFbFFVTVZPUWRzT2VMd0ZuY3lMRU1aRFE0Ck0xU3M3M2MzY0Q5eCt3TytibzNy
            dytTbmRKVFp4SFd4aDR6QUZ4SkZVTE0KLS0tIE55cFFrc0x5Q0ZRWExidStCOWlO
            bjZHTVFyNDc1eUpwbE8wZ2ZPa0NPRWsKzZmL41I1RumvacSUqS7vuLHAl1vBweX7
            IZTt46UkxeMafRzW5ekP1kfPEXHkH1n04MbdWOwvoPoxF3DkesXkbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:565IfBeGyFjAuj0d84EZa3a6pFJhpl3r2PoZcGh6r/FDbUJAhWsFvUkMFFrtRCBAdOosTunCqJFGcHMGUSeH8LR+QuknzpXEgsEGUG3l9OksKkxj1zCgf8a5MfHiCEL0f+89lCzd7NDsrCZcJFHLj0eAcBK1IJ/9e+l4QtfViGs=,iv:ES21lTan2WYfIRl5sAjiWDFvedn8iLTAljc2S/KFSuY=,tag:rEaHjF1DbvuBN7x1No/+ZA==,type:str]
    version: 3.13.3
