apiVersion: v1
kind: Secret
metadata:
    name: registry-http
    namespace: registry
type: Opaque
data:
    secret: ENC[AES256_GCM,data:R+v2tI+RJRGdgs/ESIASU8M6W4zeBz9yuZAeUTJFb0pNd8S9H2PuDLB56gXEqB582wctI+riGqlSTdUeJxNP0U+Sy7/ZPSog/DwPtfH21kL2eOHfWxzvXQ==,iv:3tfAX7wF/IsKZ01cHVE3/3vXDzvBv+4362WBAZAaPQs=,tag:5WYKNql9NbzJ7hz3N+heJg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWWozWnRoTEZwSVVxcDZ2
            bVVKbCtvcWFNOE1EYk5nbjNaYUdyajNKOGpzCnB6R0h4akord2pJc2Y0bXB2K0RP
            T01rb29iVFVrRlczUGQrTnJnVWd0NmsKLS0tIGdYbllXbCtldVExZks2YUMycGNl
            Q3d6b2V5SXArUFk2dXE1RkxhMklsVUkK5bneu4YVjcSmM02QVFHcmYsrYRZczXBw
            SjMPQQUrzDLIijELkyAEtavB76l0oDI6XMrixQ1B1CuR6epT7CjZJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:Qb7/40/wiLiuRSbaxeZJf+Urh7DKIl5wUlYPkUEntOCGqH/N+jIdmKDh5cZ8HqdrIqwH1ykBGYor05oHkGCxrV95xoQAT7mU/DnCkSeTkSp6aug9BKPtBfgDwi9Lyldzqtq1AYK8WhZqY8HxKcPLpGXCY9uWge9EkDkrFtKT/9s=,iv:0Le1sQmy522oY8Mb09aRwDOW3rcXRPbp8t2IPoHMZ9M=,tag:xOsyKXIFEArQX9R+chxTwA==,type:str]
    version: 3.13.3
