apiVersion: v1
kind: Secret
metadata:
    name: registry-creds
    namespace: yarn
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:3QMd6T2VEs70bakB22lw7v3l99T8ub3tk+oG9TjEAYg2Je4NLKM2sdGPwDEFutemKxn53tP0sk2reLghGlt7mXUI28yzGz1DrtBTXiBsdG8PztjOeolY+6dNz0t/xZR3xoOqsigH5gqxlyFCqeoDZSpuoQqQPyvGOeeNJTpx4/auPmo/jFRDUAy6P2zdMvLIgKWF3npA2veuW5ICt9u4wJWhDAjFPTz0VJ5Ohf4qdwrg0PYo,iv:yLabWOocRKaCPvGioIdjfQd8KnTe0XdNSHWQr9h+eCc=,tag:fJW9U86SvYdnJphomR3DGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBna0ViSytKcEREaEFBS3Ay
            UjNvNVpUSFRQU0Z5OXRXSDRlbFR4RXRnWDNnClFNRVhrQk9jMlkzaHVobko5b3Ey
            R0h6WjI4SFQrRnBmTlltNVhNZGZxTDgKLS0tIEVKS3VBNzNBcW1XWk5GcDFJYVlZ
            ZUxsUEYyN3huK2pCVHVzSHFCQ3ladFUKMhS+lLB9VWpqCvDcsrbl8d1K0ZucmO9F
            GqCSskdGZSoU5pexllixZb13nt+VIm+DE6vs/2/XyKAQF9NsNRg51g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:U0ZPcQtHLs+ik6nZIX+xvFQx2/U7+oIWwXScBRb8ZaVhF+cyXCiBVgXkRS9+yN7X/BR9WUWOQHK5yjPLNd0kMNHuG5R6kQRL00fMTZ2HivoZ6cA6Ppt+ROZmUQtIGnYeLjqqcaHX1wWx1q1w07d2nW0w9j/yp5vkkS5/8tNZi7U=,iv:tG71c9cb5WLj+QrAF8BcN3PmdJdwptd/UGYydkXNwuU=,tag:SCuQvUsRd7v9xieJ5TvRag==,type:str]
    version: 3.13.3
