apiVersion: v1
kind: Secret
metadata:
    name: yarn-garage
    namespace: yarn
type: Opaque
data:
    access_key: ENC[AES256_GCM,data:IqbsOVFwxmgCUK7fVh8UC3wQxGcJveoBNnwC+BehN1I+7bRD,iv:iXw2etPUAH7YE4hSvEhhbLY7NxD/DeD9sPRBngWJu38=,tag:MXCob7IVKQcw6DW72vnrlg==,type:str]
    bucket: ENC[AES256_GCM,data:6AsubN0tMBNcMUWS,iv:EtVlwxBGFhqv/iDuLWV/vslqoYszudaU7eWsVDEY3Mw=,tag:vfY78ei/CaUHKgEE/DsFGQ==,type:str]
    endpoint: ENC[AES256_GCM,data:MxX1czjHpewV9w8nouqKsfBE/GBzdxOODmglEIZFaQUusea/hhmvpVz/tdCqTVYbPYYgCZ+hi1EDEBzpWzSAtsLdLJ8=,iv:A23RWf3ZLIqo8PULMZrhzQDHSPDJjOU3wfFWN9AZocw=,tag:MbdQgC+ClEKC/TI3CzETpg==,type:str]
    endpoint_external: ENC[AES256_GCM,data:Qt5TtwdZfe8PZW+Qodnnc3XgPoeVs2SUmBr5ewu+aZRgdKG3,iv:hRLxLdCczEaHXOhDLLlbogvck2Mp96ZQyhZFQKhhA/8=,tag:4/gvBd+NdpKE035CuPYX7g==,type:str]
    secret_key: ENC[AES256_GCM,data:vpMbaiJynhiVeFtMi+hVWKGsbDn8wLxLFR8hB1k0ir3YLHIHeUCyXwPd/rD7BWreoUM9Mgve1R8PHAi2A/lfw4t9s2zFJ2axOuRMn2/P1Imx+fa6dnK2Ug==,iv:uO0N2feT+Zwk3pOMpdQcGQ7rBrBKRKs+omOmWyyY+40=,tag:P2yJVRMi1KugpdKrrqdeaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbWFlelNLY2g4N1NrMmtH
            OXJNakZYTUVqK3pKaU84bUJPaEh6WGZScHdvClJJYW5wbTBQZE11Vk9PVS80Ry80
            b3Z2T2tzM3dMZkh3ZmFoMEN6aXNRdncKLS0tIDFLOEZXb3h0ZXUxQVJYMkR0YzdK
            empoYUtlV3UyQzZhdkQydytHQVluazAKIntcVMJxvcI/LLDvknt7s0BJxL8ZORsy
            06WQ6AUA2s/HPaAfpmuFJjyatsljyX9NRE/9dqGk7K60tCF/bA3T2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1m530e4zxqtaul455myzut6cqqj39ecvtgzdw3uf59j7xdu9he4fs83w9mq
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:34:47Z"
    mac: ENC[AES256_GCM,data:Vd5/e+iY/vNj+2z2ZBp3VYT0NaMDikSVcalghNijXvHS8N+Aja+6HaNBf30RbDKP2TV0CiFekEiN0HXXRO9sVFQeQ4xcX2/1eLeW+pagRUPh6ca5wmR93MgMKumHQg4ITNrAy8Y/OxVw99ySrGZqsXlQA1MTU/b3D9Z75hv4cZo=,iv:JuJ/veq9jAmU9MgY+z69Tjy5NKAK2EhS5OJhpr6QYaU=,tag:/c7wYGIJ8oqX0Wtj/kVxaA==,type:str]
    version: 3.13.3
